# Page settings

baseURL = "https://uncleben006.github.io/resume/"
languageCode = "en"
title = "Resume of Ben Wang"
theme = "devresume"
publishDir = "docs"
# googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "王柏元 Ben Wang"
        tagline = "Engineer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Xindian"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "0966527002"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "uncleben006@gmail.com"
        # [[params.contact.list]]
        # icon = "fas fa-globe"
        # url = "#"
        # text = "www.yourwebsite.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Vue/Knockout"
        [[params.skills.list.items]]
        details = "CSS/Bootstrap/Sass"
        [[params.skills.list.items]]
        details = "Python/PHP"        
        [[params.skills.list.items]]
        details = "MySQL"
        [[params.skills.list.items]]
        details = "Laravel/Magento"      
        [[params.skills.list.items]]
        details = "linux/ubuntu/nginx/docker"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Continuous improvement"
        [[params.skills.list.items]]
        details = "Focus on teamwork" 
        [[params.skills.list.items]]
        details = "Effective communication"               
        [[params.skills.list.items]]
        details = "Strong sense responsibility"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Information and Communication"
        university = "Shih Hsin University"
        dates = "2013 - 2017"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Chinese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Learning"
        [[params.interests.list]]
        name = "Badmintion"
        [[params.interests.list]]
        name = "Travelling"     








    [params.summary]
        enable = true
        text = "I am always passionate about self-improvement. In the past three years in HTC, I have continued to study the knowledge of network management and the front-end and back-end languages. Also work with our team and became familiar with the process of website setup, development and deployment, and have the opportunity to mantain and develop multiple projects. It is a great experience for me to learn so much and work with so many excellent people. I believe I can use my experience and the knowledges to help your team grow. Also, I look forward to the new values and growth we can bring together."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Engineer"
        dates = "2019 - 2020"
        company = "HTC"
        details = "After I assist more project , I was transferred to E-Commerce team and starting to work as an Engineer. Our team focus on E-Commerce develop and we use magento as our main platform."

        [[params.experience.list]]
        title = "Specialist"
        dates = "2017 - 2019"
        company = "HTC"
        details = "After graduation, I was transferred to full-time job. In addition to the original work, I also started to assist in the development. Participated in many projects. "

        [[params.experience.list]]
        title = "Contractor"
        dates = "2017 - 2017"
        company = "HTC"
        details = "I was hired as a contractor while studying. In charge of maintaining the official website using front-end languages."

        [[params.experience.list]]
        title = "Database Operator"
        dates = "2015 - 2016"
        company = "Mandarin Library & Information Service Co., Ltd."
        details = "I work here as a part time job when I was a student. Mainly responsible for creating and maintaining the citation data for TCI-HSS (Taiwan Citation index - Human and Social Sciences).The citation is the reference material of various academic papers like journal articles, doctoral thesis. Used as one of a standard to calculate the value of academic papers."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Django"
        meta = "Content manager"
        tagline = "We implement Django as content management system for HTC official website. I test and maintain the system as a content manager. Responsible for the product information setting and translation of the global official website, and also to adjust the website content according to the activity time between regions."

        [[params.projects.list]]
        title = "Developer Hub"
        meta = "Developer"
        tagline = "This website is for developers, and the information inside includes various VR-related SDKs and development document. While the developer browses the website, we expect to contact with the developer and collect their information. For example, if the developer wants to cooperate with HTC. They can apply for a cooperation form and ask for various kind of help."
        tagline2 = "At the time we implement Salesforce for our CRM. I was there to help transfer the old developer data to Salesforce, and established a form builder system associated with Salesforce in the background. All fields correspond to the Salesforce API and can be directly store into the platform after submit."

        [[params.projects.list]]
        title = "VIVE eCommerce"
        meta = "Developer"
        tagline = "HTC has used magento 1 as its online trading platform for a long time, but until 2019 it was decided to upgrade to mangento 2, which is a big project. In addition to M1 and M2 is fundamentally disign in different way, the system configuration for different regions is also different. There is no way to upgrade all of the countries at once. And I was lucky to have the chance to participate in the upgration of TW and EU."
        tagline2 = ""

        [[params.projects.list]]
        title = "VIVELAND Webpos"
        meta = "Developer"
        tagline = "This system is an online cash register. It help Syntrend VIVELAND to record their daily revenue. I was in charge to maintain the system and create various report for sales team to reference. Worth memthion is that webpos only had the ability to record revenue. So we let it integrate with VIVELAND's member system to achieve cumulative member spending. Hope that in the future, specific discounts can be made for specific members according to the amount of consumption. "










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/uncleben006"
        title = "uncleben006"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/uncleben006"
        title = "uncleben006"
        # [[params.social.list]]
        # icon = "fab fa-twitter-square"
        # url = "//twitter.com/username"
        # title = "@username"





